const CONFIG = {
  org: {
    name: "RedWeek",
    tagline: "The Timeshare Marketplace",
  },
  resorts: [
    "Palms at Aruba",
    "Coronado Shores",
    "Blue Ridge Summit",
    "Maui Kai",
    "Sedona Canyon Club",
  ],
  regions: ["Caribbean", "Southwest", "Mountain West", "Hawaii"],
  resortRegionMap: {
    "Palms at Aruba":     "Caribbean",
    "Coronado Shores":    "Southwest",
    "Blue Ridge Summit":  "Mountain West",
    "Maui Kai":           "Hawaii",
    "Sedona Canyon Club": "Southwest",
  },
  scale: {
    totalAccounts:         3_100_000,
    linkedAccounts:        1_860_000,
    ownerOnly:               340_000,
    renterOnly:              590_000,
    resaleOnly:              310_000,
    allThree:                280_000,
    totalRenters:            890_000,
    renterConvertedResale:   160_000,
    sankeyResearched:        400_000,
    sankeyOffered:           240_000,
    travelerIdRate:               73,
    matchConfidence:              91,
    sampleSize:                3_000,
  },
  palette: {
    navy:  "#1B2A4A",
    blue:  "#2E618F",
    slate: "#5B7FA6",
    teal:  "#972417",
    teal2: "#C0392B",
    coral: "#D85F52",
    gray:  "#8B96A5",
    gray2: "#C5CBD4",
  },
  p3rl: {
    badgeLabel: "Powered by P3RL Identity Resolution",
  },
};
